In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
from zipfile import ZipFile as s

In [3]:

file_name = '/content/gdrive/MyDrive/fer2013.zip'

with s(file_name, 'r') as zi:
  zi.extractall()
  print('Done')

Done


In [4]:

file_name = '/content/gdrive/MyDrive/fer2013.csv.zip'

with s(file_name, 'r') as zi:
  zi.extractall()
  print('Done')

Done


In [6]:
import pandas as pd
import os

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Conv2D, Flatten, Dropout, MaxPooling2D, BatchNormalization, Conv3D, MaxPooling3D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras import regularizers, optimizers
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [8]:
train_datagen=ImageDataGenerator(rescale=1./255.,horizontal_flip=True, vertical_flip=True, rotation_range=60, zoom_range=0.3)

train_generator = train_datagen.flow_from_directory(
    directory=r"/content/data/train",
    target_size=(48, 48),
    color_mode="grayscale",
    batch_size=128,
    class_mode="categorical",
    shuffle=True,
    seed=42
)

Found 28709 images belonging to 7 classes.


In [90]:
test_datagen=ImageDataGenerator(rescale=1./255.)

test_generator = test_datagen.flow_from_directory(
    directory=r"/content/data/test",
    target_size=(48, 48),
    color_mode="rgb",
    batch_size=128,
    class_mode='categorical',
    shuffle=False,
    seed=42
)

Found 3589 images belonging to 7 classes.


In [10]:
val_datagen = ImageDataGenerator(rescale=1./255)
val_set = val_datagen.flow_from_directory('/content/data/val',
                                                batch_size=64,
                                                target_size=(48,48),
                                                shuffle=True,
                                                color_mode='grayscale',
                                                class_mode='categorical')

Found 3589 images belonging to 7 classes.


In [11]:
batch_size = 128

In [9]:

from keras.preprocessing import image
#from keras.applications.resnet50 import preprocess_input, decode_predictions
from keras.layers import Dense, GlobalAveragePooling2D
from keras.models import Model
from keras.optimizers import Adam
from keras.utils import to_categorical


In [31]:
base_model = tf.keras.applications.resnet50.ResNet50(weights= None, include_top=False )

In [22]:
# for layer in base_model.layers:
#     layer.trainable = False

In [19]:
x = base_model.output

In [ ]:
# x = base_model.output
# x = GlobalAveragePooling2D()(x)
# x = Dropout(0.7)(x)

In [20]:
x = Dense(64, activation='relu')(x)

In [32]:
predictions = Dense(7, activation= 'softmax')(x)


In [33]:
model = tf.keras.Model(inputs = base_model.input, outputs = predictions)


In [ ]:
#model.summary()

In [34]:
model.compile(optimizer=optimizers.Adam(lr=0.0001, decay=1e-6),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
history = model.fit(
        train_generator,
        validation_data = val_set,     
        epochs=10,  
        batch_size=batch_size ,          
        )

In [41]:
!unzip /content/model_weights_vgg16.h5.zip


Archive:  /content/model_weights_vgg16.h5.zip
  inflating: model_weights_vgg16.h5  


In [ ]:
vgg_model = tf.keras.applications.vgg16.VGG16(weights=None, input_shape= (48,48, 1))

In [ ]:
x = vgg_model.output
predictions = Dense(7, activation= 'softmax')(x)


In [ ]:
model_vgg = tf.keras.Model(inputs = vgg_model.input, outputs = predictions)


In [ ]:
model_vgg.compile(optimizer=optimizers.Adam(lr=0.0001, decay=1e-6),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
history1 = model_vgg.fit(
        train_generator,
        validation_data = val_set,     
        epochs=10,  
        batch_size=batch_size     
        )

Epoch 1/10
225/225 [==============================] - 32s 128ms/step - loss: 1.9297 - accuracy: 0.2503 - val_loss: 1.9183 - val_accuracy: 0.2494
Epoch 2/10
225/225 [==============================] - 26s 117ms/step - loss: 1.9135 - accuracy: 0.2513 - val_loss: 1.9077 - val_accuracy: 0.2494
Epoch 3/10
225/225 [==============================] - 26s 115ms/step - loss: 1.9036 - accuracy: 0.2513 - val_loss: 1.8986 - val_accuracy: 0.2494
Epoch 4/10
225/225 [==============================] - 26s 116ms/step - loss: 1.8950 - accuracy: 0.2513 - val_loss: 1.8907 - val_accuracy: 0.2494
Epoch 5/10
225/225 [==============================] - 26s 117ms/step - loss: 1.8874 - accuracy: 0.2513 - val_loss: 1.8837 - val_accuracy: 0.2494
Epoch 6/10
225/225 [==============================] - 26s 116ms/step - loss: 1.8806 - accuracy: 0.2513 - val_loss: 1.8774 - val_accuracy: 0.2494
Epoch 7/10
225/225 [==============================] - 26s 116ms/step - loss: 1.8745 - accuracy: 0.2513 - val_loss: 1.8718 - val_ac

In [ ]:
ef_model = tf.keras.applications.EfficientNetB1(weights=None, input_shape= (48,48, 1))

In [ ]:
x = ef_model.output
predictions = Dense(7, activation= 'softmax')(x)
model_ef = tf.keras.Model(inputs = ef_model.input, outputs = predictions)


In [ ]:
model_ef.compile(optimizer=optimizers.Adam(lr=0.0001, decay=1e-6),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
history2 = model_ef.fit(
        train_generator,
        validation_data = val_set,     
        epochs=20,  
        batch_size=batch_size     
        )

Epoch 1/20
225/225 [==============================] - 33s 147ms/step - loss: 1.7305 - accuracy: 0.2898 - val_loss: 1.7190 - val_accuracy: 0.2937
Epoch 2/20
225/225 [==============================] - 33s 146ms/step - loss: 1.7294 - accuracy: 0.2894 - val_loss: 1.7249 - val_accuracy: 0.2956
Epoch 3/20
225/225 [==============================] - 33s 147ms/step - loss: 1.7252 - accuracy: 0.2921 - val_loss: 1.7499 - val_accuracy: 0.2703
Epoch 4/20
225/225 [==============================] - 33s 147ms/step - loss: 1.7252 - accuracy: 0.2902 - val_loss: 1.7301 - val_accuracy: 0.2920
Epoch 5/20
225/225 [==============================] - 34s 149ms/step - loss: 1.7246 - accuracy: 0.2906 - val_loss: 1.7056 - val_accuracy: 0.3023
Epoch 6/20
225/225 [==============================] - 34s 149ms/step - loss: 1.7234 - accuracy: 0.2921 - val_loss: 1.7092 - val_accuracy: 0.3001
Epoch 7/20
225/225 [==============================] - 34s 149ms/step - loss: 1.7231 - accuracy: 0.2926 - val_loss: 1.7140 - val_ac

In [47]:
mn_model = tf.keras.applications.MobileNet(weights=None, include_top=False, input_shape= (48,48, 3))

In [49]:
x = mn_model.output
predictions = Dense(7, activation= 'softmax')(x)
model_mn = tf.keras.Model(inputs = mn_model.input, outputs = predictions)


In [50]:
model_mn.compile(optimizer=optimizers.Adam(lr=0.0001, decay=1e-6),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
model_mn.summary()

In [ ]:
model

In [ ]:
history3 = model_mn.fit(
        train_generator,
        validation_data = val_set,     
        epochs=30,  
        batch_size=batch_size     
        )

In [114]:
model_mn.predict(test_generator)

29/29 [==============================] - 1s 39ms/step


array([[[[0.15312019, 0.14462271, 0.13035324, ..., 0.1275358 ,
          0.16151854, 0.14791377]]],


       [[[0.11743845, 0.12712896, 0.14580484, ..., 0.13761283,
          0.12717263, 0.19653457]]],


       [[[0.14506242, 0.14425403, 0.12797058, ..., 0.1310324 ,
          0.15737335, 0.15649256]]],


       ...,


       [[[0.1461754 , 0.13952896, 0.13900827, ..., 0.11943528,
          0.17284171, 0.16509937]]],


       [[[0.13276711, 0.1419584 , 0.13739078, ..., 0.13979968,
          0.14125797, 0.16408451]]],


       [[[0.17021242, 0.14872675, 0.12679935, ..., 0.09949949,
          0.17246214, 0.17057748]]]], dtype=float32)

In [81]:
from sklearn.metrics import classification_report


In [ ]:
Y_test = np.argmax(y_test, axis=1) # Convert one-hot to index
y_pred = model.predict_classes(x_test)
print(classification_report(Y_test, y_pred))

In [126]:
y_pred = model_mn.predict(test_generator)
y_pred = np.argmax(y_pred, axis=-1)

29/29 [==============================] - 1s 41ms/step


In [129]:
y_pred = model_mn.predict(test_generator)

29/29 [==============================] - 1s 42ms/step


In [127]:
y_pred = np.argmax(y_pred, axis=1)

In [128]:
y_pred[0]

array([0])

In [93]:
class_labels = train_generator.class_indices


In [94]:
class_labels = {v:k for k,v in class_labels.items()}


In [95]:
target_names = list(class_labels.values())


In [ ]:
print(classification_report(train_generator.classes, y_pred, target_names=target_names))


              precision    recall  f1-score   support

           0       0.14      0.11      0.13      3995
           1       0.00      0.00      0.00       436
           2       0.15      0.10      0.12      4097
           3       0.25      0.24      0.24      7215
           4       0.17      0.23      0.20      4830
           5       0.11      0.12      0.11      3171
           6       0.18      0.20      0.19      4965

    accuracy                           0.18     28709
   macro avg       0.14      0.14      0.14     28709
weighted avg       0.17      0.18      0.17     28709



In [91]:
y_pred = model_mn.predict(test_generator)
y_pred = np.argmax(y_pred, axis=1)

29/29 [==============================] - 1s 39ms/step


In [113]:
y_pred[50]

array([[0, 0, 0, 0, 0, 0, 0]])

In [ ]:
print(classification_report(test_generator.classes, y_pred, target_names=target_names))


In [105]:
train_generator.classes

0

In [102]:
test_generator.classes

array([0, 0, 0, ..., 6, 6, 6], dtype=int32)

In [ ]:
for i in range(test_generator.classes.shape[0]):
  if test_generator.classes[i] == 0 or test_generator.classes[i] == 1 or test_generator.classes[i] == 2 or test_generator.classes[i] == 3 or test_generator.classes[i] == 4 or test_generator.classes[i] == 5 or test_generator.classes[i] == 6:
    print(test_generator.classes[i])

In [ ]:
test_generator.class_indices